#include <windows.h>
#include <stdio.h>
HINSTANCE mHinst = 0, mHinstDLL = 0;
extern "C" UINT_PTR mProcs[226] = {0};


LPCSTR mImportNames[] = {"sqlite3_aggregate_context", "sqlite3_aggregate_count", "sqlite3_auto_extension", "sqlite3_backup_finish", "sqlite3_backup_init", "sqlite3_backup_pagecount", "sqlite3_backup_remaining", "sqlite3_backup_step", "sqlite3_bind_blob", "sqlite3_bind_blob64", "sqlite3_bind_double", "sqlite3_bind_int", "sqlite3_bind_int64", "sqlite3_bind_null", "sqlite3_bind_parameter_count", "sqlite3_bind_parameter_index", "sqlite3_bind_parameter_name", "sqlite3_bind_text", "sqlite3_bind_text16", "sqlite3_bind_text64", "sqlite3_bind_value", "sqlite3_bind_zeroblob", "sqlite3_blob_bytes", "sqlite3_blob_close", "sqlite3_blob_open", "sqlite3_blob_read", "sqlite3_blob_reopen", "sqlite3_blob_write", "sqlite3_busy_handler", "sqlite3_busy_timeout", "sqlite3_cancel_auto_extension", "sqlite3_changes", "sqlite3_clear_bindings", "sqlite3_close", "sqlite3_close_v2", "sqlite3_collation_needed", "sqlite3_collation_needed16", "sqlite3_column_blob", "sqlite3_column_bytes", "sqlite3_column_bytes16", "sqlite3_column_count", "sqlite3_column_database_name", "sqlite3_column_database_name16", "sqlite3_column_decltype", "sqlite3_column_decltype16", "sqlite3_column_double", "sqlite3_column_int", "sqlite3_column_int64", "sqlite3_column_name", "sqlite3_column_name16", "sqlite3_column_origin_name", "sqlite3_column_origin_name16", "sqlite3_column_table_name", "sqlite3_column_table_name16", "sqlite3_column_text", "sqlite3_column_text16", "sqlite3_column_type", "sqlite3_column_value", "sqlite3_commit_hook", "sqlite3_compileoption_get", "sqlite3_compileoption_used", "sqlite3_complete", "sqlite3_complete16", "sqlite3_config", "sqlite3_context_db_handle", "sqlite3_create_collation", "sqlite3_create_collation16", "sqlite3_create_collation_v2", "sqlite3_create_function", "sqlite3_create_function16", "sqlite3_create_function_v2", "sqlite3_create_module", "sqlite3_create_module_v2", "sqlite3_data_count", "sqlite3_db_config", "sqlite3_db_filename", "sqlite3_db_handle", "sqlite3_db_mutex", "sqlite3_db_readonly", "sqlite3_db_release_memory", "sqlite3_db_status", "sqlite3_declare_vtab", "sqlite3_enable_load_extension", "sqlite3_enable_shared_cache", "sqlite3_errcode", "sqlite3_errmsg", "sqlite3_errmsg16", "sqlite3_errstr", "sqlite3_exec", "sqlite3_expired", "sqlite3_extended_errcode", "sqlite3_extended_result_codes", "sqlite3_file_control", "sqlite3_finalize", "sqlite3_free", "sqlite3_free_table", "sqlite3_get_autocommit", "sqlite3_get_auxdata", "sqlite3_get_table", "sqlite3_global_recover", "sqlite3_initialize", "sqlite3_interrupt", "sqlite3_key", "sqlite3_key_v2", "sqlite3_last_insert_rowid", "sqlite3_libversion", "sqlite3_libversion_number", "sqlite3_limit", "sqlite3_load_extension", "sqlite3_log", "sqlite3_malloc", "sqlite3_malloc64", "sqlite3_memory_alarm", "sqlite3_memory_highwater", "sqlite3_memory_used", "sqlite3_mprintf", "sqlite3_msize", "sqlite3_mutex_alloc", "sqlite3_mutex_enter", "sqlite3_mutex_free", "sqlite3_mutex_leave", "sqlite3_mutex_try", "sqlite3_next_stmt", "sqlite3_open", "sqlite3_open16", "sqlite3_open_v2", "sqlite3_os_end", "sqlite3_os_init", "sqlite3_overload_function", "sqlite3_prepare", "sqlite3_prepare16", "sqlite3_prepare16_v2", "sqlite3_prepare_v2", "sqlite3_profile", "sqlite3_progress_handler", "sqlite3_randomness", "sqlite3_realloc", "sqlite3_realloc64", "sqlite3_rekey", "sqlite3_rekey_v2", "sqlite3_release_memory", "sqlite3_reset", "sqlite3_reset_auto_extension", "sqlite3_result_blob", "sqlite3_result_blob64", "sqlite3_result_double", "sqlite3_result_error", "sqlite3_result_error16", "sqlite3_result_error_code", "sqlite3_result_error_nomem", "sqlite3_result_error_toobig", "sqlite3_result_int", "sqlite3_result_int64", "sqlite3_result_null", "sqlite3_result_text", "sqlite3_result_text16", "sqlite3_result_text16be", "sqlite3_result_text16le", "sqlite3_result_text64", "sqlite3_result_value", "sqlite3_result_zeroblob", "sqlite3_rollback_hook", "sqlite3_rtree_geometry_callback", "sqlite3_rtree_query_callback", "sqlite3_set_authorizer", "sqlite3_set_auxdata", "sqlite3_shutdown", "sqlite3_sleep", "sqlite3_snprintf", "sqlite3_soft_heap_limit", "sqlite3_soft_heap_limit64", "sqlite3_sourceid", "sqlite3_sql", "sqlite3_status", "sqlite3_step", "sqlite3_stmt_busy", "sqlite3_stmt_readonly", "sqlite3_stmt_status", "sqlite3_strglob", "sqlite3_stricmp", "sqlite3_strnicmp", "sqlite3_table_column_metadata", "sqlite3_test_control", "sqlite3_thread_cleanup", "sqlite3_threadsafe", "sqlite3_total_changes", "sqlite3_trace", "sqlite3_transfer_bindings", "sqlite3_update_hook", "sqlite3_uri_boolean", "sqlite3_uri_int64", "sqlite3_uri_parameter", "sqlite3_user_add", "sqlite3_user_authenticate", "sqlite3_user_change", "sqlite3_user_data", "sqlite3_user_delete", "sqlite3_value_blob", "sqlite3_value_bytes", "sqlite3_value_bytes16", "sqlite3_value_double", "sqlite3_value_int", "sqlite3_value_int64", "sqlite3_value_numeric_type", "sqlite3_value_text", "sqlite3_value_text16", "sqlite3_value_text16be", "sqlite3_value_text16le", "sqlite3_value_type", "sqlite3_vfs_find", "sqlite3_vfs_register", "sqlite3_vfs_unregister", "sqlite3_vmprintf", "sqlite3_vsnprintf", "sqlite3_vtab_config", "sqlite3_vtab_on_conflict", "sqlite3_wal_autocheckpoint", "sqlite3_wal_checkpoint", "sqlite3_wal_checkpoint_v2", "sqlite3_wal_hook", "sqlite3_win32_is_nt", "sqlite3_win32_mbcs_to_utf8", "sqlite3_win32_set_directory", "sqlite3_win32_sleep", "sqlite3_win32_utf8_to_mbcs", "sqlite3_win32_write_debug"};
BOOL WINAPI DllMain( HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpvReserved ) {
	mHinst = hinstDLL;
	if ( fdwReason == DLL_PROCESS_ATTACH ) {
		mHinstDLL = LoadLibrary( "ori_sqlite3.dll" );
		if ( !mHinstDLL )
			return ( FALSE );
		for ( int i = 0; i < 226; i++ )
			mProcs[ i ] = (UINT_PTR)GetProcAddress( mHinstDLL, mImportNames[ i ] );
	} else if ( fdwReason == DLL_PROCESS_DETACH ) {
		FreeLibrary( mHinstDLL );
	}
	return ( TRUE );
}



extern "C" void sqlite3_aggregate_context_wrapper();
extern "C" void sqlite3_aggregate_count_wrapper();
extern "C" void sqlite3_auto_extension_wrapper();
extern "C" void sqlite3_backup_finish_wrapper();
extern "C" void sqlite3_backup_init_wrapper();
extern "C" void sqlite3_backup_pagecount_wrapper();
extern "C" void sqlite3_backup_remaining_wrapper();
extern "C" void sqlite3_backup_step_wrapper();
extern "C" void sqlite3_bind_blob_wrapper();
extern "C" void sqlite3_bind_blob64_wrapper();
extern "C" void sqlite3_bind_double_wrapper();
extern "C" void sqlite3_bind_int_wrapper();
extern "C" void sqlite3_bind_int64_wrapper();
extern "C" void sqlite3_bind_null_wrapper();
extern "C" void sqlite3_bind_parameter_count_wrapper();
extern "C" void sqlite3_bind_parameter_index_wrapper();
extern "C" void sqlite3_bind_parameter_name_wrapper();
extern "C" void sqlite3_bind_text_wrapper();
extern "C" void sqlite3_bind_text16_wrapper();
extern "C" void sqlite3_bind_text64_wrapper();
extern "C" void sqlite3_bind_value_wrapper();
extern "C" void sqlite3_bind_zeroblob_wrapper();
extern "C" void sqlite3_blob_bytes_wrapper();
extern "C" void sqlite3_blob_close_wrapper();
extern "C" void sqlite3_blob_open_wrapper();
extern "C" void sqlite3_blob_read_wrapper();
extern "C" void sqlite3_blob_reopen_wrapper();
extern "C" void sqlite3_blob_write_wrapper();
extern "C" void sqlite3_busy_handler_wrapper();
extern "C" void sqlite3_busy_timeout_wrapper();
extern "C" void sqlite3_cancel_auto_extension_wrapper();
extern "C" void sqlite3_changes_wrapper();
extern "C" void sqlite3_clear_bindings_wrapper();
extern "C" void sqlite3_close_wrapper();
extern "C" void sqlite3_close_v2_wrapper();
extern "C" void sqlite3_collation_needed_wrapper();
extern "C" void sqlite3_collation_needed16_wrapper();
extern "C" void sqlite3_column_blob_wrapper();
extern "C" void sqlite3_column_bytes_wrapper();
extern "C" void sqlite3_column_bytes16_wrapper();
extern "C" void sqlite3_column_count_wrapper();
extern "C" void sqlite3_column_database_name_wrapper();
extern "C" void sqlite3_column_database_name16_wrapper();
extern "C" void sqlite3_column_decltype_wrapper();
extern "C" void sqlite3_column_decltype16_wrapper();
extern "C" void sqlite3_column_double_wrapper();
extern "C" void sqlite3_column_int_wrapper();
extern "C" void sqlite3_column_int64_wrapper();
extern "C" void sqlite3_column_name_wrapper();
extern "C" void sqlite3_column_name16_wrapper();
extern "C" void sqlite3_column_origin_name_wrapper();
extern "C" void sqlite3_column_origin_name16_wrapper();
extern "C" void sqlite3_column_table_name_wrapper();
extern "C" void sqlite3_column_table_name16_wrapper();
extern "C" void sqlite3_column_text_wrapper();
extern "C" void sqlite3_column_text16_wrapper();
extern "C" void sqlite3_column_type_wrapper();
extern "C" void sqlite3_column_value_wrapper();
extern "C" void sqlite3_commit_hook_wrapper();
extern "C" void sqlite3_compileoption_get_wrapper();
extern "C" void sqlite3_compileoption_used_wrapper();
extern "C" void sqlite3_complete_wrapper();
extern "C" void sqlite3_complete16_wrapper();
extern "C" void sqlite3_config_wrapper();
extern "C" void sqlite3_context_db_handle_wrapper();
extern "C" void sqlite3_create_collation_wrapper();
extern "C" void sqlite3_create_collation16_wrapper();
extern "C" void sqlite3_create_collation_v2_wrapper();
extern "C" void sqlite3_create_function_wrapper();
extern "C" void sqlite3_create_function16_wrapper();
extern "C" void sqlite3_create_function_v2_wrapper();
extern "C" void sqlite3_create_module_wrapper();
extern "C" void sqlite3_create_module_v2_wrapper();
extern "C" void sqlite3_data_count_wrapper();
extern "C" void sqlite3_db_config_wrapper();
extern "C" void sqlite3_db_filename_wrapper();
extern "C" void sqlite3_db_handle_wrapper();
extern "C" void sqlite3_db_mutex_wrapper();
extern "C" void sqlite3_db_readonly_wrapper();
extern "C" void sqlite3_db_release_memory_wrapper();
extern "C" void sqlite3_db_status_wrapper();
extern "C" void sqlite3_declare_vtab_wrapper();
extern "C" void sqlite3_enable_load_extension_wrapper();
extern "C" void sqlite3_enable_shared_cache_wrapper();
extern "C" void sqlite3_errcode_wrapper();
extern "C" void sqlite3_errmsg_wrapper();
extern "C" void sqlite3_errmsg16_wrapper();
extern "C" void sqlite3_errstr_wrapper();
extern "C" void sqlite3_exec_wrapper();
extern "C" void sqlite3_expired_wrapper();
extern "C" void sqlite3_extended_errcode_wrapper();
extern "C" void sqlite3_extended_result_codes_wrapper();
extern "C" void sqlite3_file_control_wrapper();
extern "C" void sqlite3_finalize_wrapper();
extern "C" void sqlite3_free_wrapper();
extern "C" void sqlite3_free_table_wrapper();
extern "C" void sqlite3_get_autocommit_wrapper();
extern "C" void sqlite3_get_auxdata_wrapper();
extern "C" void sqlite3_get_table_wrapper();
extern "C" void sqlite3_global_recover_wrapper();
extern "C" void sqlite3_initialize_wrapper();
extern "C" void sqlite3_interrupt_wrapper();
extern "C" int sqlite3_key_wrapper(int* db, void* pKey, int nKey);
extern "C" int sqlite3_key_v2_wrapper(int* db, char* zDbName, void* pKey, int nKey);
extern "C" void sqlite3_last_insert_rowid_wrapper();
extern "C" void sqlite3_libversion_wrapper();
extern "C" void sqlite3_libversion_number_wrapper();
extern "C" void sqlite3_limit_wrapper();
extern "C" void sqlite3_load_extension_wrapper();
extern "C" void sqlite3_log_wrapper();
extern "C" void sqlite3_malloc_wrapper();
extern "C" void sqlite3_malloc64_wrapper();
extern "C" void sqlite3_memory_alarm_wrapper();
extern "C" void sqlite3_memory_highwater_wrapper();
extern "C" void sqlite3_memory_used_wrapper();
extern "C" void sqlite3_mprintf_wrapper();
extern "C" void sqlite3_msize_wrapper();
extern "C" void sqlite3_mutex_alloc_wrapper();
extern "C" void sqlite3_mutex_enter_wrapper();
extern "C" void sqlite3_mutex_free_wrapper();
extern "C" void sqlite3_mutex_leave_wrapper();
extern "C" void sqlite3_mutex_try_wrapper();
extern "C" void sqlite3_next_stmt_wrapper();
extern "C" void sqlite3_open_wrapper();
extern "C" void sqlite3_open16_wrapper();
extern "C" void sqlite3_open_v2_wrapper();
extern "C" void sqlite3_os_end_wrapper();
extern "C" void sqlite3_os_init_wrapper();
extern "C" void sqlite3_overload_function_wrapper();
extern "C" void sqlite3_prepare_wrapper();
extern "C" void sqlite3_prepare16_wrapper();
extern "C" void sqlite3_prepare16_v2_wrapper();
extern "C" void sqlite3_prepare_v2_wrapper();
extern "C" void sqlite3_profile_wrapper();
extern "C" void sqlite3_progress_handler_wrapper();
extern "C" void sqlite3_randomness_wrapper();
extern "C" void sqlite3_realloc_wrapper();
extern "C" void sqlite3_realloc64_wrapper();
extern "C" int sqlite3_rekey_wrapper(int* db, void* pKey, int nKey);
extern "C" int sqlite3_rekey_v2_wrapper(int* db, char* zDbName, void* pKey, int nKey);
extern "C" void sqlite3_release_memory_wrapper();
extern "C" void sqlite3_reset_wrapper();
extern "C" void sqlite3_reset_auto_extension_wrapper();
extern "C" void sqlite3_result_blob_wrapper();
extern "C" void sqlite3_result_blob64_wrapper();
extern "C" void sqlite3_result_double_wrapper();
extern "C" void sqlite3_result_error_wrapper();
extern "C" void sqlite3_result_error16_wrapper();
extern "C" void sqlite3_result_error_code_wrapper();
extern "C" void sqlite3_result_error_nomem_wrapper();
extern "C" void sqlite3_result_error_toobig_wrapper();
extern "C" void sqlite3_result_int_wrapper();
extern "C" void sqlite3_result_int64_wrapper();
extern "C" void sqlite3_result_null_wrapper();
extern "C" void sqlite3_result_text_wrapper();
extern "C" void sqlite3_result_text16_wrapper();
extern "C" void sqlite3_result_text16be_wrapper();
extern "C" void sqlite3_result_text16le_wrapper();
extern "C" void sqlite3_result_text64_wrapper();
extern "C" void sqlite3_result_value_wrapper();
extern "C" void sqlite3_result_zeroblob_wrapper();
extern "C" void sqlite3_rollback_hook_wrapper();
extern "C" void sqlite3_rtree_geometry_callback_wrapper();
extern "C" void sqlite3_rtree_query_callback_wrapper();
extern "C" void sqlite3_set_authorizer_wrapper();
extern "C" void sqlite3_set_auxdata_wrapper();
extern "C" void sqlite3_shutdown_wrapper();
extern "C" void sqlite3_sleep_wrapper();
extern "C" void sqlite3_snprintf_wrapper();
extern "C" void sqlite3_soft_heap_limit_wrapper();
extern "C" void sqlite3_soft_heap_limit64_wrapper();
extern "C" void sqlite3_sourceid_wrapper();
extern "C" void sqlite3_sql_wrapper();
extern "C" void sqlite3_status_wrapper();
extern "C" void sqlite3_step_wrapper();
extern "C" void sqlite3_stmt_busy_wrapper();
extern "C" void sqlite3_stmt_readonly_wrapper();
extern "C" void sqlite3_stmt_status_wrapper();
extern "C" void sqlite3_strglob_wrapper();
extern "C" void sqlite3_stricmp_wrapper();
extern "C" void sqlite3_strnicmp_wrapper();
extern "C" void sqlite3_table_column_metadata_wrapper();
extern "C" void sqlite3_test_control_wrapper();
extern "C" void sqlite3_thread_cleanup_wrapper();
extern "C" void sqlite3_threadsafe_wrapper();
extern "C" void sqlite3_total_changes_wrapper();
extern "C" void sqlite3_trace_wrapper();
extern "C" void sqlite3_transfer_bindings_wrapper();
extern "C" void sqlite3_update_hook_wrapper();
extern "C" void sqlite3_uri_boolean_wrapper();
extern "C" void sqlite3_uri_int64_wrapper();
extern "C" void sqlite3_uri_parameter_wrapper();
extern "C" void sqlite3_user_add_wrapper();
extern "C" void sqlite3_user_authenticate_wrapper();
extern "C" void sqlite3_user_change_wrapper();
extern "C" void sqlite3_user_data_wrapper();
extern "C" void sqlite3_user_delete_wrapper();
extern "C" void sqlite3_value_blob_wrapper();
extern "C" void sqlite3_value_bytes_wrapper();
extern "C" void sqlite3_value_bytes16_wrapper();
extern "C" void sqlite3_value_double_wrapper();
extern "C" void sqlite3_value_int_wrapper();
extern "C" void sqlite3_value_int64_wrapper();
extern "C" void sqlite3_value_numeric_type_wrapper();
extern "C" void sqlite3_value_text_wrapper();
extern "C" void sqlite3_value_text16_wrapper();
extern "C" void sqlite3_value_text16be_wrapper();
extern "C" void sqlite3_value_text16le_wrapper();
extern "C" void sqlite3_value_type_wrapper();
extern "C" void sqlite3_vfs_find_wrapper();
extern "C" void sqlite3_vfs_register_wrapper();
extern "C" void sqlite3_vfs_unregister_wrapper();
extern "C" void sqlite3_vmprintf_wrapper();
extern "C" void sqlite3_vsnprintf_wrapper();
extern "C" void sqlite3_vtab_config_wrapper();
extern "C" void sqlite3_vtab_on_conflict_wrapper();
extern "C" void sqlite3_wal_autocheckpoint_wrapper();
extern "C" void sqlite3_wal_checkpoint_wrapper();
extern "C" void sqlite3_wal_checkpoint_v2_wrapper();
extern "C" void sqlite3_wal_hook_wrapper();
extern "C" void sqlite3_win32_is_nt_wrapper();
extern "C" void sqlite3_win32_mbcs_to_utf8_wrapper();
extern "C" void sqlite3_win32_set_directory_wrapper();
extern "C" void sqlite3_win32_sleep_wrapper();
extern "C" void sqlite3_win32_utf8_to_mbcs_wrapper();
extern "C" void sqlite3_win32_write_debug_wrapper();

int sqlite3_key(int* db, void* pKey, int nKey)
{
	int value = sqlite3_key_wrapper(db,pKey,nKey);
	sqlite3_rekey_wrapper(db, NULL, 0);
	return value;
}
